### ISSUE TITLE
Consider enlarging the board

### ISSUE THREAD

**Issue by joostschouppe** [osmbe/community_planning#1]
We're three, we're all motivated, but we're lacking time. More people would be welcome.
This requires an official meeting to change the bylaws. An official meeting requires sending out an agenda at least two weeks in advance. Physical presence is not necessary.

**Comment by xivk** [comment]
Is this really a requirement? Isn't this more of an issue of getting other to help?

**Comment by joostschouppe** [comment]
True, it isn't really. But it might make it more "fulfulling" to do said work.

**Comment by joostschouppe** [comment]
Let's close this until we feel a need
