### ISSUE TITLE
Make stickers for the Belgian mappers

### ISSUE THREAD

**Issue by pietervdvn** [osmbe/community_planning#10]
... or ask Dorothea to bring a box to CCC

**Comment by jbelien** [comment]
I asked stickers to Dorothea for OSCAL'18 but she replied that OSMF doesn't send stickers anymore.
She sent me the PDF files of the OSMF logo.

I used https://www.stickermule.com/ to print the stickers, the quality is really good but maybe you know other printing company.

**Comment by jbelien** [comment]
https://www.stickermule.com/eu/products/square-stickers
