### ISSUE TITLE
Switch from Trello to GitHub project boards

### ISSUE THREAD

**Issue by jbelien** [osmbe/community_planning#13]
In the goal to simplify our organization, I think we could/should migrate from [Trello](https://trello.com/b/VAMdaGsp/openstreetmap-belgium) to [GitHub project boards](https://help.github.com/articles/about-project-boards/) and use the GitHub project board(s) on this repository for community related tasks and dedicated repository for project related tasks.

What do you think ?

**Comment by pietervdvn** [comment]
Good for me. One 'shower thought': we increase our dependencies on Github this way. But as this is not very critical, I don't really mind.

**Comment by jbelien** [comment]
True !
But we noticed that we (OSMBE) have plenty (too much) accounts here and there so my idea was to merge Trello and GitHub since we already use a lot our GitHub organization and GitHub now provides what Trello provides :)

**Comment by joostschouppe** [comment]
I have been using this issue tracker as a project tool. For simple
projects, that's enough. But for "overview level" management, Github
projects seems just fine.

Op ma 8 okt. 2018 09:30 schreef Jonathan Beliën <notifications@github.com>:

**Comment by jbelien** [comment]
Okay, I'll spend some time in the next few days to migrate open tasks from Trello to here ! :)

**Comment by joostschouppe** [comment]
I would suggest contacting the people with outstanding tasks/projects there
to add them here if needed, maybe give them a deadline. Or we could not
delete but just archive everything...

**Comment by jbelien** [comment]
Good idea to contact the people "in charge" of the open tasks 👍 

Didn't plan to delete Trello account but just "copy" the tasks from Trello to here so we can have "everything" in one single place.

**Comment by jbelien** [comment]
Here it is : https://github.com/orgs/osmbe/projects/3
