### ISSUE TITLE
Migration domain names to Digital Ocean

### ISSUE THREAD

**Issue by jbelien** [osmbe/community_planning#15]
**osm.be**

- [x] [osm.be](https://github.com/osmbe/website)
- [x] [www.osm.be](https://github.com/osmbe/website)
- [x] mail.osm.be (+ MX record) (@xivk)
- [x] [bike4brussels.osm.be](https://github.com/oSoc18/bike4brussels) (@xivk + @oSoc18)
- [x] [community.osm.be](https://github.com/jbelien/oci-viewer) (@jbelien)
- [x] crab-import.osm.be (@gplv2)
- [x] [cyclenetworks.osm.be](https://github.com/oSoc17/rideaway-data) (@xivk + @oSoc17)
- [x] [members.osm.be](https://github.com/jbelien/mailchimp-osm) (@jbelien)
- [x] [opf.osm.be](https://github.com/ubipo/opf) (@ubipo)
- [x] [play.osm.be](https://github.com/osmbe/play) (@joostschouppe)
- [x] [road-completion.osm.be](https://github.com/osmbe/road-completion-frontend) (@xivk + @oSoc18)
- [x] [tile.osm.be](https://github.com/jbelien/openstreetmap-carto-be) (@jbelien)
- [x] [welcome.osm.be](https://github.com/osmbe/osm-welcome-belgium) (@M1dgard + @gplv2)
- [ ] calendar.osm.be (@jbelien) : *Moved to https://openstreetmap.be/calendar.html*
- [ ] [cyclerouting-api.osm.be](https://github.com/oSoc17/rideaway-backend) (@xivk + @oSoc17)
- [ ] develop.osm.be
- [ ] level0.osm.be (@M1dgard ?)
- [ ] [osoc.osm.be](https://github.com/oSoc17/rideaway-frontend) (@xivk + @oSoc17) : *Moved to https://rideaway.netlify.com/*
- [ ] roads.osm.be
- [ ] roads-tiles.osm.be
- [ ] routeplanner.osm.be
- [ ] control.osm.be (*related to former DNS provider*)
- [ ] de.control.osm.be (*related to former DNS provider*)
- [ ] jhb.control.osm.be (*related to former DNS provider*)
- [ ] k1._domainkey.osm.be (*related to former DNS provider*)
- [ ] imap.osm.be (*related to email - don't think we need it since emails will be migrated*)
- [ ] pop.osm.be (*related to email - don't think we need it since emails will be migrated*)
- [ ] relay.osm.be (*related to email - don't think we need it since emails will be migrated*)
- [ ] smtp.osm.be (*related to email - don't think we need it since emails will be migrated*)

**openstreetmap.be**

- [x] [openstreetmap.be](https://github.com/osmbe/website)
- [x] [www.openstreetmap.be](https://github.com/osmbe/website)
- [x] [tile.openstreetmap.be](https://github.com/jbelien/openstreetmap-carto-be) (@jbelien)

**Comment by jbelien** [comment]
I migrated the main/most important sub domains !

I think we should clean it a bit :)

@xivk @joostschouppe Which one do you need to migrate ?

Let's try the find the people behind every domain name.

**Comment by jbelien** [comment]
Once we are sure the migration is complete, I'll make openstreetmap.be our **main** domain name 👍

**Comment by gplv2** [comment]
crab-import.osm.be does not resolve.  this should not be too hard imho,  the records just needed to be transfered along.   I find this a bit strange, since these aren't really subdomains, they are just host records under the given domains (osm.be / openstreetmap.be).    crab-import was a CNAME to aptum.bitless.be , that way I can move/shuffle manage my servers without intervention on DNS level by managing my own domain(s).  Let me know if I can help here, I worked as chief DNS on ISP level for years, I know a thing or two on subject of DNS I've been told.

**Comment by jbelien** [comment]
Hi @gplv2 , thanks for your help but I just didn't migrate `crab-import` record yet.
I was waiting to be sure needed it (which I guessed :P).

It's now migrated and working 👍

**Comment by jbelien** [comment]
> Once we are sure the migration is complete, I'll make openstreetmap.be our **main** domain name 👍

Done ! 🎉
