### ISSUE TITLE
Migration server to Digital Ocean

### ISSUE THREAD

**Issue by jbelien** [osmbe/community_planning#16]
Here is a list of services that could be migrated to Digital Ocean and regrouped :

- [x] PHP : [community.osm.be](https://github.com/jbelien/oci-viewer) (@jbelien)
- [x] PHP : [members.osm.be](https://github.com/jbelien/mailchimp-osm) (@jbelien)
- [x] PHP : [welcome.osm.be](https://github.com/osmbe/osm-welcome-belgium) (@M1dgard / @gplv2)
- [ ] ??? : [cyclenetworks.osm.be](https://github.com/oSoc17/rideaway-data) (@xivk + @oSoc17) (see #26)

What else ?
@xivk ? @joostschouppe ?

**Comment by jbelien** [comment]
https://welcome.osm.be/ is down again.

I think it would be a good idea to migrate the important tools to a single server (possibly managed by OKBE).

**Comment by xivk** [comment]
I have always been a huge fan of migrating all this to OKBE. I don't really have anything else to add.

**Comment by archived-m** [comment]
All of this can be hosted on the OpenStreetMap organisation on DigitalOcean, with OKBE billing. I'd prefer it if we shared management, given that you know most about the tools.

This is the same place you manage your DNS

**Comment by jbelien** [comment]
> 
> All of this can be hosted on the OpenStreetMap organisation on DigitalOcean, with OKBE billing. I'd prefer it if we shared management, given that you know most about the tools.
> 
> This is the same place you manage your DNS

That's perfect !
I'll manage and setup/install the server 👍

**Comment by jbelien** [comment]
Server is live!
I'll start the migration ASAP 🎉

**Comment by jbelien** [comment]
Migration of https://members.osm.be/ and https://community.osm.be/ is completed ! 🍾

**Comment by jbelien** [comment]
https://welcome.osm.be/ has been migrated! 🥳
