### ISSUE TITLE
OpenBelgium 2019

### ISSUE THREAD

**Issue by jbelien** [osmbe/community_planning#18]
[OpenBelgium 2019](http://2019.openbelgium.be/) will take place on 2nd (Community day) and 4th March 2019 ("Conference" day).

I think we should use that opportunity to promote OSMBE !

Ideas:

- Booth
- Dedicated track
- Mapathon
- Introduction to OSM
- Introduction to OSMBE
- Talks

---

# Booth

The idea is to have a more dynamic booth than last year !
We have a bit of money now so we can print lots of stickers (OSM + OSMBE). I usually use https://www.stickermule.com/ (but alternative are welcome if necessary).

An idea was also to ask people to map their house (of something else is their house is already mapped). That way, we can show them how easy it is to edit using iD !
My idea was to print a map of Belgium (A3 format ?) where each province is divided in "puzzle pieces" ; each time someone map something, he/she can highlight a piece of the puzzle where they mapped ; so, we will have kind of a race to see which province was mapped more during the 2 days.
Each time someone map something, he/she would receive something (is a sticker enough ?).
**EDIT 2018-12-21:** maybe printed mugs or tote bags would be nice as a gift for those who mapped something.

# Branding

- [x] Stickers
- [x] T-Shirts
- [x] High visibility jackets

# Dedicated track / Talks (Conference day)

- Introduction to OpenStreetMap
- Introduction to OpenStreetMap Belgium
- [Why you should switch to OSM ?](https://jbelien.github.io/talks/why-and-how-to-switch-to-openstreetmap-for-your-website/)

See https://github.com/osmbe/community_planning/issues/18#issuecomment-457114330

# Activity (Community day)

- Mapathon (area to define)
- *Walking meetup* (see https://github.com/osmbe/community_planning/issues/18#issuecomment-452755102)

See https://github.com/osmbe/community_planning/issues/18#issuecomment-457111238

**Comment by pietercolpaert** [comment]
I think @xivk might also do a session on a research project we’re doing for routing over OSM

**Comment by jbelien** [comment]
> I think @xivk might also do a session on a research project we’re doing for routing over OSM

Would be awesome indeed :)

**Comment by xivk** [comment]
Yes, I plan to talk about https://openplanner.team/ at least!

**Comment by xivk** [comment]
The deadline for talks is this friday... we need to another call for talks. I'm guessing we don't have a dedicated track?

**Comment by pietervdvn** [comment]
I already signed up to give an intro to OSM. Furthermore, I brought a few stickers (>30) from CCC too which I'll bring. I can also man the booth a few hours. 

I also invited Victor Shcherb (maker of OsmAnd) to come, so he might be there too!

**Comment by jbelien** [comment]
Awesome idea from @marcgemis :

> I cannot make it to Open Belgium, but I have been thinking about a "walking meetup" for some time now. So instead of sitting in a pub, doing a walk and talk about OSM and survey techniques and apply them.
>
> Taking that idea, on a community day, it could be a workshop about surveying techniques, JOSM tips, micromapping, that kind of stuff. It would be an hand-on workshop, where people have to go outside for 15 minutes or so and collect data. Afterwards compare techniques, collected data and do a bit of mapping. Perhaps discuss a bit about usefulness, special maps, ...

**Comment by jbelien** [comment]
Christophe is working on design for the t-shirt and the high visibility jacket.
He is also working on adding "OpenStreetMap Belgium" underneath our logo for the stickers.

- https://github.com/osmbe/community_planning/issues/19
- https://github.com/osmbe/community_planning/issues/9
- https://github.com/osmbe/community_planning/issues/10

🎉🎉🎉

**Comment by joostschouppe** [comment]
Program proposal for the community day:
* Introduction - OSM/OSMbe
> 10:00-10:15, @pietervdvn 
* Mapathon: missing maps in Belgium
> Description: "Learn the basics of mapping while putting missing villages on the map!"
> 10:15-11:15, @jbelien and @joostschouppe 
> mission: map empty villages in Wallonia based on imagery and public basemaps
* Indoor Mapping:
> Description: "An introduction to indoor mapping - and an invitation to map this building, today!"
> 11:15-11:30, Lionel 
* Making thematic maps for beginners with Overpass-Turbo
> Description: "OSM is data, not just maps. Learn how to extract live subsets of data (security cameras, playgrounds, cafés with wifi) and show them on an always up to date map. Use the same map as a mobile data editing app."
> 11:30-12:30, @joostschouppe 
> workshop using Overpass-Turbo and MapContrib

LUNCH BREAK

* Picture mapping: learn how to map anything using street level imagery
> Description: "Learn how to look at publicly available pictures to scan for anything mapable"
> 13:30-14:00, @joostschouppe 
* Use free-beer tiles on your website: a how-to
> 14:00-15:00, @jbelien 
> Description: "OpenStreetMap Belgium offers free tiles for your website. Learn how to use them!"
* Free podium / mapping time
> 15:00-15:30, Your Name Here
* Indoor mapping: show the results
> We mapped this building today, let's see what it looks like now
> 15:30-15:45, Lionel
* Closing words
> 15:45-16:00

**Comment by joostschouppe** [comment]
Program proposal for the 90 minutes OSM session in the 150 people room at the Open Belgium professional day:

* Crazy about mapping : what is OpenStreetMap (OSM) and what is OSMbe doing
> Description: "We will give a short introduction to what OpenStreetMap is all about and specifically what OpenStreetMap Belgium is doing - introducing OSMbe/projects".
> Speakers: "Pieter Vander Vennet et al."
> content: intro, osmbe status, donations, osoc
* OSMbe projects: Switch to OpenStreetMap
> Description: "OpenStreetMap Belgium offers free tiles for use on your website. We will explain why and how we did this, and why and how you can use them"
> Speaker: Jonathan Beliën
* OSMbe projects: Being the first to map new things
> Description: "OpenStreetMap wants to be the best map of the world. Part of that is keeping up with changes. Here we will explain how government info and open data help us do that. Case in point: how we handled massive address changes when municipalities merge before it even happened."
> content: (address changes; grb import; road completion)
> Speakers: Joost Schouppe et al.
