### ISSUE TITLE
Make high visibility jacket for the Belgian mappers

### ISSUE THREAD

**Issue by jbelien** [osmbe/community_planning#19]
https://www.printsimple.eu/en-be/clothing/safety-garments/fluoflash-hi-vis-safety-garment

**Comment by jbelien** [comment]
OSMUK for reference: https://osmuk.org/product/osm-uk-hi-vis-vest/

**Comment by joostschouppe** [comment]
Community feedback: one already ordered; please not yellow; please "keep it serious" and professional looking
