### ISSUE TITLE
Importing the public bookcases database of Noreen

### ISSUE THREAD

**Issue by pietervdvn** [osmbe/community_planning#20]
Together with @s8evq, we have started with placing nodes where there is a public bookcase according to [Noreen's database](http://users.telenet.be/noreen/Noreen/Vlaamse_boekenkasten.htm). (We got his permission to copy it all after a friendly mail.)

This issue thread aims to track progress of the import. 

[The overview sheet can be found here](https://ethercalc.org/gday02l9wv)

## Open questions:

- [ ] How to tag 'Geefkasten'? A public shack where people drop their old goods, toys, ... to exchange, similar to books?

## Fancy maps and stats

- [Pietervdvn's quickmap](http://pietervdvn.github.io/Quickmaps/Bookcases/Bookcases.html?area=Belgie)
- [Ici.be](https://ici.be/cat:public_bookcase/nl) (has a nice table and counters)

**Comment by jbelien** [comment]
Awesome project @pietervdvn ! :)

Just for reference, could you copy the (part of the) email giving permission to use her database ?
Thanks !

**Comment by pietervdvn** [comment]
> In principe heb ik er niets op tegen dat jullie de gegevens van mijn website gebruiken.

(In principle, I don't mind if the data of my website are being used)

This is the only line which is really about giving permission. Other parts of the mail are about technicalities.

**Comment by hgcvm** [comment]
The same framacalc is now updated and holds the information for all Flemish provinces.

**Comment by pietervdvn** [comment]
I've found a 'wild' bookcase today - one that wasn't mentioned elsewhere!

**Comment by hgcvm** [comment]
I have moved from framacalc to ethercalc.org, as framacalc is shutting down 6 july 2020.
https://ethercalc.org/gday02l9wv

**Comment by bxl-forever** [comment]
How shall we deal with the dozens of notes that have been hanging for about a year?  Some bookcases could not be found and we do not have enough mappers with enough time to do all the surveys.
Either we organise a special mapathon for public bookcases or we should clean up.

**Comment by jbelien** [comment]
@bxl-forever Good point! I asked myself the same question a few days ago.

I think we can just close the remaining open notes about this topic.

**Comment by hgcvm** [comment]
If you close the notes, does it mean the bookcase doesn't exist, or has not been surveyed?

I'm closely keeping track of the notes in East- and West Flanders. It's a very slow process. Once in a while, I get a message about a note being closed from somebody who happened to pass by the location and found it or did not find it.

It would be a pity to close all the notes, without alternative system to keep track of them.

I understand all the open notes on the map look very messy

**Comment by hgcvm** [comment]
I'm going over the ones in Brussels and closing if somebody replied it wasn't found (and keeping track in ethercalc)

**Comment by hgcvm** [comment]
According to the ethercalc, these notes are still open in Brussels:
https://www.openstreetmap.org/note/1792216
https://www.openstreetmap.org/note/1792216
https://www.openstreetmap.org/note/1792218
https://www.openstreetmap.org/note/1792219
https://www.openstreetmap.org/note/1792220
https://www.openstreetmap.org/note/1794086
https://www.openstreetmap.org/note/1794172
https://www.openstreetmap.org/note/1795034
https://www.openstreetmap.org/note/1835631
https://www.openstreetmap.org/note/1893722
https://www.openstreetmap.org/note/1893724
https://www.openstreetmap.org/note/1895123
https://www.openstreetmap.org/note/1895127
https://www.openstreetmap.org/note/1895128
https://www.openstreetmap.org/note/1895130
https://www.openstreetmap.org/note/2024840

(small statistics: out of the possible 103 public bookcases, we have:
36% confirmed and mapped
7% confirmed as non existant
16% note still left open
and for remaining 41%, we didn't even add a note yet)
not bad at all i think :)

**Comment by pietervdvn** [comment]
I've made a new 'quickmap' for bookcases: https://pietervdvn.github.io/MapComplete/bookcases.html?z=14&lat=50.850&lon=4.3611

**Comment by joostschouppe** [comment]
I think this project is as complete as it is going to get
Worth a blogpost though
