### ISSUE TITLE
National mapathon 2019

### ISSUE THREAD

**Issue by joostschouppe** [osmbe/community_planning#21]
Still a lot to organize:

- [x] Make sure we have all the details. Check https://lite.framacalc.org/NDfQlySZTg
- [ ] Find volunteers for all locations
- [x] Set up eventbrite: https://mapathon2019.eventbrite.com/
- [ ] Invite newsletter subscribers
- [x] Coordinate with Red Cross Vlaanderen
- [ ] Review the documentation at https://www.dropbox.com/sh/qvg9m5unqkyspko/AAAml8T8JBOahA6HjLIbPU58a?dl=0

During the event, we will use the Riot tasks channel to coordinate: https://riot.im/app/#/room/#osmbe-task:matrix.org

**Comment by pietervdvn** [comment]
Hey,

I noticed that the national mapathons will be during weekdays (we/th) this year. Is this intentional? 

Second: I can volunteer in Ghent, do I just add my email to the framapad?

**Comment by pietervdvn** [comment]
Also: I could ask Vives for a location in Bruges this year (at a few minutes of the station). Should I ask them or would all the different locations be to much to handle?

**Comment by joostschouppe** [comment]
Yup, just add your name and email to the framacalc.
Extra locations, I don't know. ALl the other locations are managed by the universities, so you'd be basically on your own? You can contact Frank.Canters at vub.be (uni coordinator) if you want to do that.

**Comment by jbelien** [comment]
I'll be volunteering at ULB on 27th of March ! 😃
