### ISSUE TITLE
Future of the mapper of the month project

### ISSUE THREAD

**Issue by pietervdvn** [osmbe/community_planning#24]
@escada @marcgemis has indicated that he has lost interest in running the mapper of the month project. Although it is sad to see this go, I fully understand this decision. Thanks for running it for so long!

However, this also means that we should tie up this loose end.
We should either search a new maintainer for this project, find a group of people who want to maintain it, or gracefully sunset this (and communicate to the wider community).
I myself don't have the time to take this upon me - even getting to translating one article took me months.

There are two interviews which are still in the pipeline - one originally in French, one originally in English. I've just translated the French one into English.

I propose that we still publish those (albeit without Dutch translations or without French translation for the latter one), with a maintainer request. If no one reaches out to take this over after the first article, we should add a goodbye message to the second one.

So, what (IMHO) we should still do:

- [ ] Publish one interview with a request for takeover
- [ ] Publish the other one with a request for takeover + goodbye message
- [ ] Update the [wiki page](https://wiki.openstreetmap.org/wiki/WikiProject_Belgium/Belgian_Mapper_of_the_Month) to reflect the status of the project
- [ ] Send a big thank you to escada who has done this for years

@xivk @jbelien @joostschouppe : what do you guys think?

**Comment by jbelien** [comment]
Let's try to keep this project alive!

There is https://github.com/orgs/osmbe/projects/2 that already gives us some leads for future interviews.

We can indeed publish the 2 interviews that are already ready and contact the community to see if someone is interested. 
If we don't find anyone, I think we should focus on the candidates already available and then see :)

**Comment by xivk** [comment]
Perhaps there is a way to organize the work more efficiently and get more people to contribute? 

Share the workload and we should be able to do this no? Maybe we should define what needs doing every month and see how we can organize this work to be done in smaller chunks by multiple people?

**Comment by foxandpotatoes** [comment]
As I said in my recent email ...

I am ready to discuss things again.

Please give me : 

-  the links to all the necessary files
-  the way things have been done up to now
-  up to do things in this respect

I shall appreciate and confirm if I am able to take that in charge for the moment.

Pierre

**Comment by jbelien** [comment]
Hello @foxandpotatoes ,

Thanks a lot for your interest in this project!
I invited you to the "Mapper of the Month" team ; you now have access to the [project board](https://github.com/orgs/osmbe/projects/2).

Feel free to ask if you have any question 🎉

**Comment by gplv2** [comment]
We should maybe make a website for this.  It's probably all the manual labour that takes the fun out of it.

**Comment by foxandpotatoes** [comment]
Bonjour Jonathan,

Le lien arrive sur "Error 404". Y a-t-il eu du changement ?

Bien à toi.

Pierre




Le mar. 27 août 2019 à 10:01, Jonathan Beliën <notifications@github.com> a
écrit :

**Comment by jbelien** [comment]
@foxandpotatoes I just replied via email, you need to accept the invitation to the *Mapper of the Month* team :)

**Comment by joostschouppe** [comment]
Foxandpotatoes now keeps this alive
