### ISSUE TITLE
Make a leaflet about osmbe

### ISSUE THREAD

**Issue by joostschouppe** [osmbe/community_planning#25]

**Comment by jbelien** [comment]
I think we already have some : https://github.com/osmbe/flyer

**Comment by joostschouppe** [comment]
great, but could use an update and someone to actually get it to print!

**Comment by joostschouppe** [comment]
I made a new version and had it printed. The document at Canva is available [here](https://www.canva.com/design/DAFL8ODAbFA/PN1zfLsZ7Ps-HIbarPwosA/view?utm_content=DAFL8ODAbFA&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink). Note that we have a full Canva account, because OKBE is a non-profit.
