### ISSUE TITLE
Do a funding drive

### ISSUE THREAD

**Issue by joostschouppe** [osmbe/community_planning#3]
We need a little money to make map events more fun, to pay basic hosting expenses (meetup, osm.be, servers), to pay for the occasional train for volunteers.

Subtasks:
- [x] Make donations easy ([fix this here](https://github.com/osmbe/website/issues/53))
- [ ] Write about why people should give us money
- [ ] Talk to people who might give something

**Comment by jbelien** [comment]
I stop working (at the moment) on the Slack "funding page" because I'm kind of stuck ...
Stripe API/library are more complicated than expected (security reasons ... which make sense ^^).

I guess Patreon is still an option ;
or a basic Stripe/Paypal page

**Comment by jbelien** [comment]
See https://github.com/osmbe/website/issues/53

**Comment by xivk** [comment]
A small note: Before we start doing a donation drive I think it would be best that we already have the recurring donations stuff and encourage people to do that instead of one-time donations.

**Comment by joostschouppe** [comment]
Most of this is done, and with Corporate Membership we actually have an income now
