### ISSUE TITLE
Create a corporate membership program

### ISSUE THREAD

**Issue by joostschouppe** [osmbe/community_planning#31]
What could we offer:
- mapping services (your area of interest will be promoted to the community)
- free consultancy (we will visit you and help analyse business cases that could have a relation to OSM)
- help with doing projects with the community
- visibility  (logo) on our website & events
- a chance for them to show off their open credentials

Program itself:
- yearly amount 5000EUR for larger businesses
- yearly amount 1000EUR for NGO's & small businesses (SME-definition)

**Comment by jbelien** [comment]
That would indeed be awesome to provide such service !
And I would be more than interested to be part of it (even though I'm not exactly sure how to include that in my daily job).

**Comment by joostschouppe** [comment]
See also https://osmuk.org/members/corporate-membership/

**Comment by xivk** [comment]
SME-definition: https://ec.europa.eu/growth/smes/sme-definition_en

**Comment by joostschouppe** [comment]
Hey we actually did this
