### ISSUE TITLE
Belgian postal codes

### ISSUE THREAD

**Issue by jbelien** [osmbe/community_planning#34]
_bpost_ released their dataset of postal codes 🍾 

Dataset: https://www.geo.be/catalog/details/9738c7c0-5255-11ea-8895-34e12d0f0423
WMS service: https://www.geo.be/catalog/details/2b1a3840-5263-11ea-acd1-34e12d0f0423

There are quite a lot of topological errors in the dataset though ! It will need some cleaning before being usable.

Current status in OpenStreetMap:
![image](https://user-images.githubusercontent.com/1150563/87545270-f7f3a780-c6a7-11ea-8b0b-90ead4e5b4d3.png)
-- Source: http://overpass-turbo.eu/s/W73

**Comment by pietervdvn** [comment]
The license is NOT compatible! Commercial use is _not_ allowed

**Comment by jbelien** [comment]
> The license is NOT compatible! Commercial use is not allowed

Indeed, I noticed that ! I know the guy behind the dataset (Xavier Querriau) ; I'll get in touch with him :)

**Comment by joostschouppe** [comment]
This is also not compatible: "Custodian’s name must be mentioned each time the data are being used publically."

**Comment by jbelien** [comment]
Well, forget what I said ... This is useless 😭
