### ISSUE TITLE
Belgium baselayer with only names

### ISSUE THREAD

**Issue by YorbenVerhoest** [osmbe/community_planning#35]
Greetings fellow belgians.

I am building an interactive map using leaflet and OSM, I am generating GEOJSON layers on top of my map of the communities of Belgium (see picture)

As you can see behind that, I load in a baselayer that display one names. But I don't want to show the items that falls outside of Belgium. is there any baselayer of only Belgium names?

![](https://i.stack.imgur.com/UPqf8.png)

Thanks

Yorben Verhoest

**Comment by jbelien** [comment]
Hello @YorbenVerhoest ,

We'll need more information about the layers your using.
What layer are you using for Belgium ? Is it raster or vector ?
What layer are you using for the labels/names ? Is it raster or vector ?

**Comment by YorbenVerhoest** [comment]
Hey @jbelien,

For the layers of all communities in Belgium i'm using [GeoJson ](https://leafletjs.com/reference-1.6.0.html#geojson) by leaflet to render them

for the labels/names, I'm using this link `https://{s}.basemaps.cartocdn.com/light_only_labels/{z}/{x}/{y}.png`, to generate the tiles with names/labels behind them.


**To generalise my question:**

If you follow this [link ](https://basemaps.cartocdn.com/#5/52.670/7.822)
--> hover over the circle at the bottom-right 
--> select the 3rd circle starting from left 
--> you can see a map of the world with only the names/labels of the countries, cities, ... displayed.

Is there anything available like this but only with names/labels of belgium (with the labels written in dutch), the rest should just be grey.
or is it possible / difficult to make something like this?

I'm just a starting dev, so sorry if I this is unclear, I tried to explain it at my best :)

**Comment by jbelien** [comment]
It's not possible to do what you want with `https://{s}.basemaps.cartocdn.com/light_only_labels/{z}/{x}/{y}.png`, you don't have any control over what is displayed.

I think the "easiest" way would be to use <https://overpass-turbo.eu/> to select the data you want to show as label (municipalities, towns, ...), export it as GeoJSON, and add that layer in your project.
For instance, here you have all municipalities in Belgium : https://overpass-turbo.eu/s/Xgf

**Comment by jbelien** [comment]
> For the layers of all communities in Belgium i'm using GeoJson by leaflet to render them

Another solution would be to switch to [OpenLayers](https://openlayers.org/) (instead of Leaflet).
Using OpenLayers allows you to play with labels "better" than Leaflet.
Here is an example: https://openlayers.org/en/latest/examples/vector-labels.html
