### ISSUE TITLE
Mailing-List Reader

### ISSUE THREAD

**Issue by jbelien** [osmbe/community_planning#36]
The Czech community has a clean way of presenting `talk-cz` mailing-list threads: https://openstreetmap.cz/talkcz/202008
Could be interesting to replicate!

---

- Parser they use: [`PlancakeEmailParser.php`](https://github.com/osmcz/osmcz-web/blob/master/app/service/PlancakeEmailParser.php) (source: https://github.com/daniele-occhipinti/php-email-parser)
- Email process: [`load-mails.php`](https://github.com/osmcz/osmcz-web/blob/master/load-mails.php)

Might be interesting to switch to https://github.com/php-mime-mail-parser/php-mime-mail-parser for parsing (more active/maintained than `daniele-occhipinti/php-email-parser`)

---

Our `talk-be` archive : https://lists.openstreetmap.org/pipermail/talk-be/
Example for August 2020:

- GZIP: https://lists.openstreetmap.org/pipermail/talk-be/2020-August.txt.gz
- TXT: https://lists.openstreetmap.org/pipermail/talk-be/2020-August.txt

**Comment by thibaultmol** [comment]
Just found this Apache project which actually turns a mailing list into a half decent forum almost: http://ponymail.incubator.apache.org/
Might also be interesting to take a look at

**Comment by joostschouppe** [comment]
@tkas @zbycz : did you have a look at this ponymail thing before you built your own solution? Any other hints before we try to build something here in Belgium?

**Comment by tkas** [comment]
Hi, the talk-cz presentation is a work of @zbycz, but AFAIK he just created a new solution without thinking too much about existing complete projects, mainly for the easiness of integration to the rest of our portal. If you want to use it (as a whole or as an inspiration), I see no problem with it.

**Comment by joostschouppe** [comment]
Another thought: OSMF has a paid DeepL API subscription. It would be pretty awesome if the solution would integrate translations!

**Comment by joostschouppe** [comment]
It's likely we move to community.osm.org anyway, so let's close this
