### ISSUE TITLE
Organize shared accounts

### ISSUE THREAD

**Issue by joostschouppe** [osmbe/community_planning#4]
We have lots of accounts, and it's hard to keep track of what they are used for, what the passwords are, and who has access. How to solve this?

**Comment by jbelien** [comment]
Yeah, I was asking myself the same.

Maybe we should start listing the accounts we have/need ;
Then whenever possible just share the admin (like here on GitHub) ;
For the account where it's not possible (like Twitter), I actually have no good solution ; we can try to host a protected file somewhere (OneDrive, Google Drive, ...) and share the access to that file.

**Comment by jbelien** [comment]
See https://gitlab.com/osmbe

**Comment by joostschouppe** [comment]
The gitlab solution can close this issue right? Unless we want to move it back to github now that you can have free private repositories here?

**Comment by jbelien** [comment]
> now that you can have free private repositories here?

The free private repo is not available for organizations, unfortunately.

I guess we use GitLab for now.

I spoke about it with @MichielLeyman ; OKBE uses [LastPass](https://www.lastpass.com/) for their shared password. They use the "family" subscription (6 users - 48EUR/year). That looks interesting ; definitely more secure but is it worth it ? 😋

**Comment by jbelien** [comment]
Let's try to find something a bit more secured:

- [LastPass](https://www.lastpass.com/) (suggested by @MichielLeyman)
  - Family: 48USD/year = access for 6
  - Team: 48USD/year/user
- [Bitwarden](https://bitwarden.com/) (suggested by Lionel)
  - Family: 1USD/month = limited 5
  - Team: 5USD/month
- [Dashlane](https://www.dashlane.com/)
  - 3.33EUR/month
  - 👎 Only Business account (4.00EUR/month/user) allows group sharing

---

After a few test (web version only), Bitwarden seems the most interesting!

**Comment by joostschouppe** [comment]
We're using a vault on a private repo now, this is good enough

**Comment by joostschouppe** [comment]
We're using a vault on a private repo now, this is good enough
