### ISSUE TITLE
Make a list of "top mapping tasks"

### ISSUE THREAD

**Issue by joostschouppe** [osmbe/community_planning#42]
Stuff like the GR surface theme, road completion tasks, building import, etc should be very visible on wiki and website
We have created https://wiki.openstreetmap.org/wiki/WikiProject_Belgium/top_mapping_tasks (short URL tinyurl.com/helpusmap)
Feel free to add topics there.
Conditions:
- ready for mapping
- clearly documented what needs to be done, or at least a link to a chatroom on the topic

```[tasklist]
### To do:
- [ ] promote on element
- [ ] promote on the website
- [ ] promote in the newsletter
- [ ] promote on talk-be
- [ ] make the wiki page more attractive
- [ ] ...
- [ ] success!
```

**Comment by nobohan** [comment]
From a recent call from the Walloon gov, I think mapping solar panels (with orientation, or even slope, etc.) is actually a crucial data that does not exist anywhere. It was also a quaterly project in UK. 

Possible partner is [Energie Commune](https://energiecommune.be/)

I'd personally be interested/available in starting such a project

**Comment by joostschouppe** [comment]
For the FOSS4G/SotM presentation, I quickly made https://wiki.openstreetmap.org/wiki/WikiProject_Belgium/top_mapping_tasks with short URL tinyurl.com/helpusmap

**Comment by joostschouppe** [comment]
@nobohan: your proposal is great, but it's more a candidate for [a quarterly project](https://github.com/osmbe/community_planning/issues/44) than the list of "top mapping tasks", as there is no mapping task yet

**Comment by joostschouppe** [comment]
We actually did this
