### ISSUE TITLE
Do a project about traditional sports

### ISSUE THREAD

**Issue by joostschouppe** [osmbe/community_planning#6]
We have "kegelen", "kaatsen", "staande wip", etc. We should develop better tags if needed; create some maps; talk about it with sports lovers.

**Comment by seppesantens** [comment]
That would be great. I'm also thinking about all variants of 'bollen' (staakbollen, krulbollen, boltra,...) and krachtbal. Inside intel will indeed be crucial I guess.

**Comment by pietervdvn** [comment]
The tower for Staande wip can be tagged with tower:type=popinjay

There are a few in Bruges such as:

https://www.openstreetmap.org/node/5540659558

**Comment by joostschouppe** [comment]
This would be a nice MapComplete theme, but not really needed in this list
