### ISSUE TITLE
Make T-shirts for the Belgian mappers

### ISSUE THREAD

**Issue by pietervdvn** [osmbe/community_planning#9]
It would be great to have OSM-tshirts, which we can wear at events (such as mapathons) or at meetings with municipality meetings.

It would be cool to use [the logo that Midgard created](https://welcome.osm.be/img/osm.svg)

**Comment by jbelien** [comment]
I prefer our "official" logo though (https://wiki.openstreetmap.org/wiki/File:Osm_belgium_logo.svg)

**Comment by joostschouppe** [comment]
T-shirts requiere money, so we first need to do a [funding drive](https://github.com/osmbe/community_planning/issues/3). But to do a funding drive you first need to make it easy to donate. So [this issue](https://github.com/osmbe/website/issues/53) needs to be closed first.
Of course, if anyone already wants to research the possibilities, that's totally fine.
Oh, and I also think I prefer the "official logo".

**Comment by xivk** [comment]
Yes first funding/sponsoring... but perhaps we don't have to wait for that. I know OSM France sells the t-shirts at some occasions and gives them away at others.

**Comment by jbelien** [comment]
> I know OSM France sells the t-shirts at some occasions and gives them away at others.

Yes, I like what MSF did with their "Save the World, Map it !" t-shirt.
They printed it and sold it for the price they paid for it.
That's a nice way to have t-shirt without having to pay for it (maybe we could ask to OpenKnowledge to advance us the money for that).

And we could also sell the t-shirt for a few euros (not too much though) more so it can go in our bank account.

**Comment by xivk** [comment]
So, who's up for designing a t-shirt? Perhaps we can ask one of the designers for open summer of code?

**Comment by jbelien** [comment]
> Perhaps we can ask one of the designers for open summer of code?

Definitely, I'll ask Danielle or the STIB-MIVB team if they can help :)

**Comment by joostschouppe** [comment]
Our "house style" was developped by Christophe Leroy, I could also send him a message

**Comment by jbelien** [comment]
https://www.printsimple.eu/en-be/clothing/t-shirts

I guess we can go/start with the cheapest : https://www.printsimple.eu/en-be/clothing/t-shirts/bc-e150-t-shirt
